openapi: "3.0.2"
info:
  title: Health Fit
  description: API Documentation
  contact:
    name: BE
    email: altaBE@mail.com
  version: '1.0'
servers:
  - url: https://aaryadewangga.cloud.okteto.net:8080/{entity}
    variables:
      entity:
        default: users
        enum:
          - users
          - goals
          - user history
          - foods
          - menu
          - menu details
tags:
  - name: Users
    description: Users Resgister/Update/Delete
  - name: Goals
    description: Users Goals
  - name: User History
    description: User History of Foods/Goals
  - name: Foods
    description: Foods Methods
  - name: Menus
    description: Menu 
  - name: Menus Details
    description: Menu Detail 
paths:
  /users/register:
    post:
      summary: Register New Users
      tags:
        - Users
      description: Get a New Account
      requestBody:
        required: true
        description: Create Account with valid schema
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                  format: password
                gender:
                  type: string
                  enum:
                    - Pria
                    - Wanita
              example:
                name: test
                email: test@test.com
                password: test
                gender: Pria
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      user_uid: 
                        type: string
                      name:
                        type: string
                      email:
                        type: string
                      gender:
                        type: string
                        enum:
                          - Pria
                          - Wanita
                example:
                  code: 200
                  message: success to get new Account
                  data:
                    user_uid: jksfbkjfkjabruablnlab
                    name: test
                    email: test@test.com
                    gender: Pria
        '400':
          $ref: '#/components/responses/400'
  /users/login:
    post:
      tags:
        - Users
      summary: Login user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              $ref: '#/components/schemas/UserLogin'
      responses:
        '200':
          description: User terautorisasi
          content:
            application/json:
              schema:
                type: object
              example:
                code: 200
                message: Success login, get a new token
                data:
                  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
        '500':
          description: Invalid Authorization
          content:
            application/json:
              schema:
                type: object
              example:
                code: 500
                message: There are something problem on server
                data:
  /users:
    get:
        summary: User Profile
        tags:
          - Users
        description: User Profile
        security:
          - bearerAuth: []
        responses:
          '200':
            description: OK
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    code:
                      type: integer
                      example: 200
                    message :
                      type: string
                      example: Success to get users profile
                    data:
                      type: object
                      properties:
                        user_uid:
                          type: string
                        name:
                          type: string
                        email:
                          type: string
                        password:
                          type: string
                          format: password
                        gender:
                          type: string
                          enum:
                            - Pria
                            - Wanita
                      example:
                          user_uid: jksfbkjfkjabruablnlab
                          name: test
                          email: test@test.com
                          gender: Pria
    put:
      summary: Update By ID
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              $ref: '#/components/schemas/UserInput'
            example:
              name: Test Update
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/SuccessSingleResponse'
              example:
                code: 200
                message: Success to Update User Data
        '204':
          $ref: '#/components/responses/204'
    delete:
      tags:
        - Users
      summary: delete user data
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/SuccessSingleResponse'
              example:
                code: 200
                message: success to delete user data
  /foods:
    post:
      summary: Add / Create Foods Data
      tags:
        - Foods
      requestBody:
        required: true
        description: Create / Add Rooms Data
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                category_id:
                  type: integer
                description:
                  type: string
                price:
                  type: integer
                image_id:
                  type: integer
                date_stock:
                  type: string
                total_person:
                  type: integer
                total_rooms:
                  type: integer
                size_bed:
                  type: string
                user_id:
                  type: integer
              example:
                name: Villa Mewah
                category_id: 1
                description: villa daerah dingin, 2 lantai
                price: 20000
                image_id : 1
                date_stock:
                total_person: 2
                total_rooms: 1
                size_bed: queen
                user_id: 1
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
                      category_id:
                        type: integer
                      description:
                        type: string
                      price:
                        type: integer
                      image_id:
                        type: integer
                      date_stock:
                        type: string
                      total_person:
                        type: integer
                      total_rooms:
                        type: integer
                      size_bed:
                        type: string
                      user_id:
                        type: integer
                example:
                  code: 201
                  message: sukses menambahkan produk baru
                  data:
                    id : 1
                    name: Villa Mewah
                    category_id: 1
                    description: villa daerah dingin, 2 lantai
                    price: 20000
                    image_id : 1
                    date_stock:
                    total_person: 2
                    total_rooms: 1
                    size_bed: queen
                    user_id: 1
        '400':
          $ref: '#/components/responses/400'
        '500':
          $ref: '#/components/responses/500'
    get:
      summary: Get All Rooms
      tags:
        - Rooms
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                      type: array
                      items:
                        type: object
                        properties:
                           id:
                            type: integer
                           name:
                            type: string
                           category_id:
                            type: integer
                           description:
                            type: string
                           price:
                            type: integer
                           image_id:
                            type: integer
                           date_stock:
                            type: string
                           total_person:
                            type: integer
                           total_rooms:
                            type: integer
                           size_bed:
                            type: string
                           user_id:
                            type: integer
                example:
                    code: 200
                    message: success to get all rooms
                    data:
                      - id : 1
                        name: Villa Mewah
                        category_id: 1
                        description: villa daerah dingin, 2 lantai
                        price: 20000
                        image_id : 1
                        date_stock:
                        total_person: 2
                        total_rooms: 1
                        size_bed: queen
                        user_id: 1
                      - id : 2
                        name: Villa Mewah
                        category_id: 1
                        description: villa daerah dingin, 2 lantai
                        price: 20000
                        image_id : 1
                        date_stock:
                        total_person: 2
                        total_rooms: 1
                        size_bed: queen
                        user_id: 1
  /rooms/{id}:
    get:
      summary: Update Rooms Data
      tags:
        - Rooms
      parameters:
        - name: id
          in: path
          description: ID Rooms
          required: true
          schema:
            type: integer
      security:
         - bearerAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
                      category_id:
                        type: integer
                      description:
                        type: string
                      price:
                        type: integer
                      image_id:
                        type: integer
                      date_stock:
                        type: string
                      total_person:
                        type: integer
                      total_rooms:
                        type: integer
                      size_bed:
                        type: string
                      user_id:
                        type: integer
                example:
                  code: 200
                  message: Berhasil mengupdate data produk
                  data:
                    id : 2
                    name: Villa Mewah
                    category_id: 1
                    description: villa daerah dingin, 2 lantai
                    price: 20000
                    image_id : 1
                    date_stock:
                    total_person: 2
                    total_rooms: 1
                    size_bed: queen
                    user_id: 1
    put:
      summary: Update Rooms Data
      tags:
        - Rooms
      parameters:
        - name: id
          in: path
          description: ID Rooms
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        description: Update Rooms Data
        content:
          application/json:
            schema:
              type: object
              properties:
                price:
                  type: integer
                description:
                  type: string
              example:
                price: 70000
                description: update rooms description 
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
                      category_id:
                        type: integer
                      description:
                        type: string
                      price:
                        type: integer
                      image_id:
                        type: integer
                      date_stock:
                        type: string
                      total_person:
                        type: integer
                      total_rooms:
                        type: integer
                      size_bed:
                        type: string
                      user_id:
                        type: integer
                example:
                  code: 200
                  message: Berhasil mengupdate data produk
                  data:
                    id : 2
                    name: Villa Mewah
                    category_id: 1
                    description: update rooms description
                    price: 70000
                    image_id : 1
                    date_stock:
                    total_person: 2
                    total_rooms: 1
                    size_bed: queen
                    user_id: 1
        '400':
          $ref: '#/components/responses/400'
        '401':
          description: Authorization Failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
              example:
                  code: 401
                  message: Failed User Authorization
                  data:
    delete:
      summary: Delete Rooms
      tags:
        - Rooms
      parameters:
        - name: id
          in: path
          description: ID Rooms
          required: true
          schema:
            type: integer
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
              example:
                code: 200
                message: success to delete rooms
                data:
components:
  parameters:
    UserID:
      name: id
      in: path
      required: true
      schema:
        type: integer
  schemas:
    UserLogin:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      example:
        email: test@test.com
        password: test
    UserInput:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
    SuccessSingleResponse:
      type: object
      properties:
        code:
          type: integer
        success:
          type: boolean
        message:
          type: string
        data:
          $ref: '#/components/schemas/UserInput'
  responses:
    '204':
      description: Failed to Update
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: integer
                example: 204
              message:
                type: string
                example: No data for Update
              data:
                type: object
                example: 
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: integer
              message:
                type: string
              data:
                type: object
                properties:
                  name:
                    type: string
                  email:
                    type: string
            example:
              code: 400
              message: Invalid Input
              data:
    '401':
      description: Authorization Failed
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: integer
                example: 401
              success:
                type: boolean
                example: false
              message:
                type: string
                example: invalid Email or password
              data:
                type: object
                example:
                  token: {}
    '500':
      description: Internal Server Error
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: integer
              message:
                type: string
              data:
                type: object
                properties:
                  name:
                    type: string
                  email:
                    type: string
            example:
              code: 500
              message: Something Error on Server
              data:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT